FROM amazonlinux:2

# Install Docker, AWS CLI, and jq
RUN yum update -y && \
    yum install -y docker jq unzip less && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && ./aws/install && \
    rm -rf awscliv2.zip aws && \
    yum clean all

# Verify
RUN aws --version && docker --version && jq --version

LABEL maintainer="you@example.com"
ENTRYPOINT ["/bin/bash"]
